spring:
  datasource:
    url: jdbc:mysql://192.168.22.60:3306/paascloud_omc?characterEncoding=utf8&useSSL=false
paascloud:
  aliyun:
    rocketMq:
      instanceName: systec-provider-omc
      consumerGroup: CID_OMC
      producerGroup: PID_OMC
